//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Application.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARMADA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ARMADA()
        {
            this.RITASE = new HashSet<RITASE>();
        }
    
        public string ARMADAID { get; set; }
        public string ARMADANAME { get; set; }
        public Nullable<double> ARMADACAPACITYINKG { get; set; }
        public Nullable<int> ARMADATOTALTIRE { get; set; }
        public string ARMADACOLOR { get; set; }
        public string ARMADAMERK { get; set; }
        public string SITENAME { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<short> IsActive { get; set; }
    
        public virtual SITE SITE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RITASE> RITASE { get; set; }
    }
}
