//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Application.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTRACT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CONTRACT()
        {
            this.ContractProduct = new HashSet<ContractProduct>();
            this.DeliveryRequest = new HashSet<DeliveryRequest>();
            this.FinanceTransaction = new HashSet<FinanceTransaction>();
        }
    
        public long ContractId { get; set; }
        public string ContractNumber { get; set; }
        public Nullable<int> ClientIdPK { get; set; }
        public Nullable<decimal> Value { get; set; }
        public Nullable<decimal> Line { get; set; }
        public Nullable<System.DateTime> StartPeriode { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public Nullable<System.DateTime> EndPeriode { get; set; }
        public Nullable<int> MaxExpiredDR { get; set; }
        public string SiteName { get; set; }
        public string Remark { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<short> IsActive { get; set; }
    
        public virtual CLIENT CLIENT { get; set; }
        public virtual SITE SITE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractProduct> ContractProduct { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeliveryRequest> DeliveryRequest { get; set; }
        public virtual FinanceBalance FinanceBalance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FinanceTransaction> FinanceTransaction { get; set; }
    }
}
