//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Application.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DeliveryRequest()
        {
            this.DeliveryOrder = new HashSet<DeliveryOrder>();
            this.DeliveryRequestProductDetailTransaction = new HashSet<DeliveryRequestProductDetailTransaction>();
        }
    
        public long DeliveryRequestId { get; set; }
        public string DeliveryRequestNumber { get; set; }
        public Nullable<long> ContractId { get; set; }
        public Nullable<System.DateTime> DeliveryRequestTime { get; set; }
        public string TokenToLoad { get; set; }
        public string IsActiveToken { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<short> IsActive { get; set; }
        public string Status { get; set; }
    
        public virtual CONTRACT CONTRACT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeliveryOrder> DeliveryOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeliveryRequestProductDetailTransaction> DeliveryRequestProductDetailTransaction { get; set; }
    }
}
