//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Application.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductConvertion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductConvertion()
        {
            this.TransactionProduct = new HashSet<TransactionProduct>();
        }
    
        public long ConvertionId { get; set; }
        public string ConvertionNumber { get; set; }
        public string Site { get; set; }
        public string BatchCode { get; set; }
        public string SourceProudct { get; set; }
        public Nullable<double> Ammount { get; set; }
        public Nullable<System.DateTime> ConvertionTime { get; set; }
        public string ConvertBy { get; set; }
        public string Remark { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<short> IsActive { get; set; }
    
        public virtual BATCH BATCH { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
        public virtual SITE SITE1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionProduct> TransactionProduct { get; set; }
    }
}
