//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Application.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RITASE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RITASE()
        {
            this.TransactionProduct = new HashSet<TransactionProduct>();
        }
    
        public int RITASEID { get; set; }
        public string RITASENUMBER { get; set; }
        public string SITE { get; set; }
        public string PRODUCT { get; set; }
        public string DRIVERARMADA { get; set; }
        public string ARMADA { get; set; }
        public Nullable<double> QuantityInTon { get; set; }
        public Nullable<System.DateTime> RITASETIME { get; set; }
        public string RITASESTATUS { get; set; }
        public string Remark { get; set; }
        public string BatchCode { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<short> IsActive { get; set; }
        public Nullable<int> SOURCEID { get; set; }
    
        public virtual ARMADA ARMADA1 { get; set; }
        public virtual BATCH BATCH { get; set; }
        public virtual EMPLOYEE EMPLOYEE { get; set; }
        public virtual PRODUCT PRODUCT1 { get; set; }
        public virtual SITE SITE1 { get; set; }
        public virtual SOURCE SOURCE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionProduct> TransactionProduct { get; set; }
    }
}
