//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Application.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionProduct
    {
        public long Id { get; set; }
        public string TransactionProductNumber { get; set; }
        public string ProductId { get; set; }
        public string TypeDebitOrCredit { get; set; }
        public string Jenis { get; set; }
        public Nullable<double> Ammount { get; set; }
        public Nullable<int> RitaseId { get; set; }
        public Nullable<long> AdjustmentId { get; set; }
        public Nullable<long> ConvertionId { get; set; }
        public Nullable<long> MixingId { get; set; }
        public string Remark { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<short> IsActive { get; set; }
    
        public virtual PRODUCT PRODUCT { get; set; }
        public virtual ProductAdjustment ProductAdjustment { get; set; }
        public virtual ProductConvertion ProductConvertion { get; set; }
        public virtual ProductMixing ProductMixing { get; set; }
        public virtual RITASE RITASE { get; set; }
    }
}
