//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.MainApplication.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SystemResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SystemResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Web.MainApplication.Resources.SystemResources", typeof(SystemResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tritsur Portal.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tritsur Portal.
        /// </summary>
        public static string ApplicationNameShort {
            get {
                return ResourceManager.GetString("ApplicationNameShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Views/Insurance.Bancassurance/Auxiliary/.
        /// </summary>
        public static string AuxiliaryViewPath {
            get {
                return ResourceManager.GetString("AuxiliaryViewPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Views/Insurance.Bancassurance/CommonFiles/.
        /// </summary>
        public static string CommonFileViewPath {
            get {
                return ResourceManager.GetString("CommonFileViewPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Views/Insurance.Bancassurance/Companies/.
        /// </summary>
        public static string CompaniesViewPath {
            get {
                return ResourceManager.GetString("CompaniesViewPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tritsur.
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tritsur.com.
        /// </summary>
        public static string CompanyWebSite {
            get {
                return ResourceManager.GetString("CompanyWebSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id-ID.
        /// </summary>
        public static string CultureInfoNameOfTransformator {
            get {
                return ResourceManager.GetString("CultureInfoNameOfTransformator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ApplicationCookie.
        /// </summary>
        public static string DefaultAuthenticationTypes_ApplicationCookie {
            get {
                return ResourceManager.GetString("DefaultAuthenticationTypes_ApplicationCookie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExternalBearer.
        /// </summary>
        public static string DefaultAuthenticationTypes_ExternalBearer {
            get {
                return ResourceManager.GetString("DefaultAuthenticationTypes_ExternalBearer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExternalCookie.
        /// </summary>
        public static string DefaultAuthenticationTypes_ExternalCookie {
            get {
                return ResourceManager.GetString("DefaultAuthenticationTypes_ExternalCookie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TwoFactorCookie.
        /// </summary>
        public static string DefaultAuthenticationTypes_TwoFactorCookie {
            get {
                return ResourceManager.GetString("DefaultAuthenticationTypes_TwoFactorCookie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TwoFactorRememberBrowserCookie.
        /// </summary>
        public static string DefaultAuthenticationTypes_TwoFactorRememberBrowserCookie {
            get {
                return ResourceManager.GetString("DefaultAuthenticationTypes_TwoFactorRememberBrowserCookie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home/Unauthorized;Account/Login;Account/Logoff;UserManagement/ASPNETUSERSChangePassword.
        /// </summary>
        public static string DefaultRole {
            get {
                return ResourceManager.GetString("DefaultRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1800.
        /// </summary>
        public static string ExpiredCookiesTime {
            get {
                return ResourceManager.GetString("ExpiredCookiesTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Views/Insurance.Bancassurance/FCLDetails/.
        /// </summary>
        public static string FCLDetailsViewPath {
            get {
                return ResourceManager.GetString("FCLDetailsViewPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Views/Insurance.Bancassurance/FCLs/.
        /// </summary>
        public static string FCLsViewPath {
            get {
                return ResourceManager.GetString("FCLsViewPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Account/Login.
        /// </summary>
        public static string LoginPath {
            get {
                return ResourceManager.GetString("LoginPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Account/LogOff.
        /// </summary>
        public static string LogoutPath {
            get {
                return ResourceManager.GetString("LogoutPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Views/Insurance.Bancassurance/MedicalDocs/.
        /// </summary>
        public static string MedicalDocsViewPath {
            get {
                return ResourceManager.GetString("MedicalDocsViewPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Views/Insurance.Bancassurance/MedicalsViewPath/.
        /// </summary>
        public static string MedicalsViewPath {
            get {
                return ResourceManager.GetString("MedicalsViewPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Views/Insurance.Bancassurance/MemberAdditionals/.
        /// </summary>
        public static string MemberAdditionalsViewPath {
            get {
                return ResourceManager.GetString("MemberAdditionalsViewPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Views/Insurance.Bancassurance/MemberDocuments/.
        /// </summary>
        public static string MemberDocumentsViewPath {
            get {
                return ResourceManager.GetString("MemberDocumentsViewPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Views/Insurance.Bancassurance/MemberInfoes/.
        /// </summary>
        public static string MemberInfoesViewPath {
            get {
                return ResourceManager.GetString("MemberInfoesViewPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Views/Insurance.Bancassurance/MemberLogs/.
        /// </summary>
        public static string MemberLogsViewPath {
            get {
                return ResourceManager.GetString("MemberLogsViewPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Views/Insurance.Bancassurance/MemberMasters/.
        /// </summary>
        public static string MemberMasterViewPath {
            get {
                return ResourceManager.GetString("MemberMasterViewPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Views/Insurance.Bancassurance/MemberQuisionaires/.
        /// </summary>
        public static string MemberQuisionaires {
            get {
                return ResourceManager.GetString("MemberQuisionaires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Views/Insurance.Bancassurance/PolicyMasters/.
        /// </summary>
        public static string PolicyMasterViewPath {
            get {
                return ResourceManager.GetString("PolicyMasterViewPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Views/Insurance.Bancassurance/ProductDetails/.
        /// </summary>
        public static string ProductsDetailsViewPath {
            get {
                return ResourceManager.GetString("ProductsDetailsViewPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Views/Insurance.Bancassurance/Products/.
        /// </summary>
        public static string ProdutsViewPath {
            get {
                return ResourceManager.GetString("ProdutsViewPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Views/Insurance.Bancassurance/QuisionaireDetails/.
        /// </summary>
        public static string QuisionaireDetails {
            get {
                return ResourceManager.GetString("QuisionaireDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Views/Insurance.Bancassurance/Quisionaires/.
        /// </summary>
        public static string Quisionaires {
            get {
                return ResourceManager.GetString("Quisionaires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Views/Insurance.Bancassurance/Regions/.
        /// </summary>
        public static string RegionViewPath {
            get {
                return ResourceManager.GetString("RegionViewPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Home/Unauthorized.
        /// </summary>
        public static string UnAthorizedDefaultPath {
            get {
                return ResourceManager.GetString("UnAthorizedDefaultPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account/Register.
        /// </summary>
        public static string UnAuthorizedRole {
            get {
                return ResourceManager.GetString("UnAuthorizedRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 17/02/2018.
        /// </summary>
        public static string ViewDataPathKey {
            get {
                return ResourceManager.GetString("ViewDataPathKey", resourceCulture);
            }
        }
    }
}
